### ISSUE TITLE
New config system

### ISSUE THREAD

**Issue by Norbiros** [Norbiros/emojitype#1]
## Current problems:
- It is hard to add/remove emoji entries
- You separate emoji id and emoji only by `;`
- It doesn't check for errors
- It looks bad
![Screenshot from 2023-09-30 18-49-00](https://github.com/Norbiros/emojitype/assets/89837724/3dff203b-2674-4e7c-8e57-1f4f8d2f513b)

## Solution:
I won't probably use [YetAnotherConfigLib](https://modrinth.com/mod/yacl) because it doesn't fit EmojiType needs well. So probably I will implement this system on my own.

If you have any suggestion, ideas please let me know here!

**Comment by AdielHub** [comment]
Is there a way to add emojis directly into a config file ? I haven't been able to make the screenshotted menu work at all to add custom ones lol

**Comment by Norbiros** [comment]
Yes. In your Minecraft instance you can find `config` which contains `emojitype.json`

**Comment by Norbiros** [comment]
It will probably change a bit, but most is done!

Previous:
![Screenshot from 2024-09-03 19-21-24](https://github.com/user-attachments/assets/798f2a4c-984c-478b-b4e9-40140d87c850)

New:
![Screenshot from 2024-09-03 19-21-46](https://github.com/user-attachments/assets/ba569d02-45b7-4ae2-9648-f134b7ec584e)

Also it doesn't require Cloth Config!
