### ISSUE TITLE
[Question] Why the specific Fabric Loader dependency?

### ISSUE THREAD

**Issue by Poopooracoocoo** [Norbiros/emojitype#10]
Most mods won't be affected by Fabric Loader updates but [Emoji Type 2.2.6 for 1.21](https://modrinth.com/mod/emoji-type/version/2.2.6-1.21) depends on "~0.16.0". I think a dependency on ">=0.15.11" would make more sense but I have no idea if you're actually using anything from Fabric Loader 0.16.0 so I'd appreciate clarification on this :)

relevant lines
https://github.com/Norbiros/emojitype/blob/1.21.x/fabric/src/main/resources/fabric.mod.json#L36
https://github.com/Norbiros/emojitype/blob/1.21.x/gradle.properties#L13

P.S. Also just noticed that you haven't specified that Emoji Type is client sided here https://github.com/Norbiros/emojitype/blob/1.21.x/fabric/src/main/resources/fabric.mod.json#L20

**Comment by Norbiros** [comment]
I just updated fabric loader without thinking much... Those issues should be now fixed. Thanks for noticing!
