### ISSUE TITLE
Neoforge 1.20.1 failed

### ISSUE THREAD

**Issue by liangmoe** [Norbiros/emojitype#6]
the latest emojitype (emoji-type-2.2.3+1.20.4-neoforge) somehow crashed my instances with neoforge loder, but wont crashed with the forge emojitype with neoforge loader

Neoforge emojitype latestlog: https://mclo.gs/1kHU5VI

forge emojitype latestlog(successfully launch): https://mclo.gs/jnuHdvF

**Comment by Norbiros** [comment]
> neo was not fully rebranded to neo until 20.2, so the neoforge modid does not exist in 1.20.1.

I updated releases on modrinth and curseforge to fix this problem. Thanks for reporting!
