### ISSUE TITLE
Reload command?

### ISSUE THREAD

**Issue by 4EPBRK6RK6RK** [Norbiros/emojitype#8]
Hello!
I am creating a resource pack closely related to custom symbols and your mod is a salvation for me! I will be able to abandon complex sites and use your mod!But I was faced with the need to reboot the mod config. I tried rebooting the resource packs and re-entering the world, but it didn't help, and rebooting the client is not very convenient.

Could you add something like a command or a button to reload the config?

**Comment by Norbiros** [comment]
I will solve this problem correctly in #1.

For now, after modifying the config, just open EmojiType's config menu (you need to install ClothConfig). This will automatically load all emojis from the file, essentially reloading the config. You can then close the menu without saving.
